server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /api/northwind/v1

spring:
  datasource:
    url: ${URL_DATA_BASE:jdbc:postgresql://tai.db.elephantsql.com:5432/ghahujcl}
    username: ${USERNAME_DATA_BASE:ghahujcl}
    password: ${PASSWORD_DATA_BASE:afogLwFtW8Xft9kxpen-dPIeuCWsAX1s}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: false



