server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /api/northwind/v1

spring:
  datasource:
    url: ${URL_DATA_BASE:jdbc:postgresql://ec2-54-89-105-122.compute-1.amazonaws.com:5432/d8f7a3dt77goet}
    username: ${USERNAME_DATA_BASE:xpqtnrwlfwmdnf}
    password: ${PASSWORD_DATA_BASE:7ff6516417e33412ca72a354e2eb052e1b63324b934354d75292b43d4155db0e}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none



